spring:
    application:
        name: spring-cloud-ms-persona

server:
    port: 8081
    servlet:
        context-path: /ms-persona
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/