eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: spring-cloud-ms-internal-gateway

  cloud:
    gateway:
      routes:
      - id: route_persona
        uri: lb://spring-cloud-ms-persona
        predicates:
        - Path=/mspersona/**
        filters:
        - StripPrefix=1