spring:
    application:
        name: spring-cloud-ms-discover-register
server:
    port: 8761
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        peer-node-read-timeout-ms: 6000
